### ISSUE TITLE
TypeError: 'in <string>' requires string as left operand, not NoneType

### ISSUE THREAD

**Issue by gauravphoenix** [fpietka/rds-pgbadger#2]
I am running command "rds-pgbadger my-db-instance" but getting following exception- 

```
016-11-04 08:29:36,529 :: INFO :: Getting all logs
Traceback (most recent call last):
  File "/usr/local/bin/rds-pgbadger", line 9, in <module>
    load_entry_point('rdspgbadger==1.0.2', 'console_scripts', 'rds-pgbadger')()
  File "/Library/Python/2.7/site-packages/package/rdspgbadger.py", line 117, in main
    get_all_logs(args.instance, args.output, args.date, args.region)
  File "/Library/Python/2.7/site-packages/package/rdspgbadger.py", line 84, in get_all_logs
    for log in (name for name in response.get("DescribeDBLogFiles")
  File "/Library/Python/2.7/site-packages/package/rdspgbadger.py", line 85, in <genexpr>
    if date in name["LogFileName"]):
TypeError: 'in <string>' requires string as left operand, not NoneType
```

It would seem that the error is due to missing region but my `~/.aws/config` looks like this- 

```
[default]
region = us-east-1
output = json
```

Python version - 

```
Python 2.7.10 (default, Jul 30 2016, 18:31:42)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
```

**Comment by fpietka** [comment]
It seems `response.get("DescribeDBLogFiles")` can miss the `LogFileName` key in its items.

Would it be possible for you to edit your file `/Library/Python/2.7/site-packages/package/rdspgbadger.py` and add the following after line `83`:
```python
print(response.get("DescribeDBLogFiles"))
```
Then give me the output in the issue?

What I can tell from that is I can skip log files that don't have a name, but if I could see your use case, I might come up with a better solution.

**Comment by fpietka** [comment]
@gauravphoenix nevermind, I reproduced. Should be quick to fix.

**Comment by fpietka** [comment]
@gauravphoenix I released a new version (v1.0.3) that should fix your issue.

Please let me know how it goes.

**Comment by gauravphoenix** [comment]
Thanks, error is gone.

**Comment by fpietka** [comment]
Great! thanks for the report.
