### ISSUE TITLE
1mb rds log limit

### ISSUE THREAD

**Issue by talatbaig** [fpietka/rds-pgbadger#3]
Hi,

Just wanted to ask how you got around the 1mb limit on the log file downloads?

Thanks

**Comment by fpietka** [comment]
Hi,

I'm not sure to understand. Are you experiencing issues downloading big files with the script?

**Comment by talatbaig** [comment]
yes, log files max size is 1mb when I download using rds-pgbadger but they are much bigger on aws

**Comment by fpietka** [comment]
Ok, I see what I overlooked. I'm going to fix that ASAP

**Comment by talatbaig** [comment]
thank you

**Comment by fpietka** [comment]
@talatbaig just released a new version. It should solve the problem.

Please let me know if you have any other issue.
