### ISSUE TITLE
Pass extra command-line arguments to pgbadger

### ISSUE THREAD

**Issue by mtpettyp** [fpietka/rds-pgbadger#6]
I'd like to be able to pass extra command-line arguments to pgbadger.

And example would be something like:

`rds-pgbadger my_instance -r us-east-1 --pgbadger-args '--exclude-query "^(VACUUM|COMMIT)" --top 30'`

Thoughts?  I'm more than happy to create a pull request if this is something you'd be interested in merging.

**Comment by fpietka** [comment]
Thanks a lot for your contribution!
I'll get into releasing a new version with it ASAP.
